### ISSUE TITLE
bug: RecyclerView Overlaps with BottomNavBar

### ISSUE THREAD

**Issue by s-ayush2903** [njaLocer/Locer-Android-Client#21]
**Screenshots:**
|Instance-I|Instance-II|Instance-III|
|---|---|--|
|![Screenshot_20201004-130753_LocerAndroid 1](https://user-images.githubusercontent.com/59222356/95009938-411e1c80-0643-11eb-9cc6-055e79bd5645.jpg)|![Screenshot_20201004-130826_LocerAndroid 1](https://user-images.githubusercontent.com/59222356/95009979-8f332000-0643-11eb-88a2-c2fd66fb5fac.jpg)|![Screenshot_20201004-130800_LocerAndroid 1](https://user-images.githubusercontent.com/59222356/95009970-7e82aa00-0643-11eb-922a-e9a59fe01a4f.jpg)|

**Comment by Saharatt593** [comment]
i fix it

**Comment by s-ayush2903** [comment]
Assigned!

**Comment by s-ayush2903** [comment]
Closing in #22
