### ISSUE TITLE
feat: Implement AuthFlow

### ISSUE THREAD

**Issue by s-ayush2903** [njaLocer/Locer-Android-Client#28]
* In the module, implement entry via login/registration process and also make a _Continue as a Guest_ option.
* As of now, we'll be considering firebase as a backend for our services, so make use of their docs and res.
* Try aligning UI as per the mockups provided

Ref: https://firebase.google.com/docs/auth/android/firebaseui

**Comment by Raushansingh19** [comment]
we have to make it easy and friendly. Anybody those who want to see our app,  it's features and our products they can easily go through it.

**Comment by s-ayush2903** [comment]
Fine :+1:
